//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ebook1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAndRole
    {
        public int ID { get; set; }
        public int Role_id { get; set; }
        public int User_id { get; set; }
        public string Role_name { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
